KTB-02 Распечатать строки из файла
art-cherepan/KotlinTelegramBot pull request #1
Opened 2024-12-28 00:15 UTC by art-cherepan

2024-12-28 16:43 UTC, dzenonce requested changes

2024-12-28 16:43 UTC, dzenonce commented on src/main/kotlin/lesson_1/Main.kt
> +    val fileLines = file.readLines()
Давай воспользуемся `forEachLine {}` - это будет еще и короче.

2024-12-28 16:43 UTC, dzenonce commented on src/main/kotlin/lesson_1/Main.kt
> +    file.createNewFile()
Нам **не нужно** создавать новый файл, только читать его

2024-12-28 16:43 UTC, dzenonce commented on src/main/kotlin/lesson_1/Main.kt
> +    file.appendText("""
Соответственно, нужно убрать этот код

2024-12-29 00:22 UTC, art-cherepan commented on src/main/kotlin/lesson_1/Main.kt
> +    val fileLines = file.readLines()
Исправил на `forEachLine {}`

2024-12-29 00:22 UTC, art-cherepan commented on src/main/kotlin/lesson_1/Main.kt
> +    file.createNewFile()
Исправил

2024-12-29 00:22 UTC, art-cherepan commented on src/main/kotlin/lesson_1/Main.kt
> +    file.appendText("""
Исправил

2024-12-29 15:24 UTC, dzenonce approved these changes
Отлично

2024-12-29 15:26 UTC, merged